# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WaterBodyRecognizer
                                 A QGIS plugin
 The plugin allows to recognize water bodies on satellite image.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-03
        copyright            : (C) 2021 by Mateusz Starczyk
        email                : starczyk.mateusz@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WaterBodyRecognizer class from file WaterBodyRecognizer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .water_body_recognizer import WaterBodyRecognizer
    return WaterBodyRecognizer(iface)
